layout_spectrum: 0.9862604
typography_spectrum: 0.2037037
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.5035841
  rhythmicContrast: 0.4916368
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Peterlauscher
